name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate Static Website
        run: npx nuxi generate
      
      - name: Use "github-pages-deploy-action" Action
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: dist
          token: ${{ secrets.TOKEN }}